export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const EDIT_PRODUCT_TITLE = "EDIT_PRODUCT_TITLE";
